---
name: Bug Report
description: Report a bug.
labels: bug
body:
  - type: textarea
    attributes:
      label: Summary
    validations:
      required: true

  - type: textarea
    attributes:
      label: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    attributes:
      label: What actually happened?
    validations:
      required: true

  - type: textarea
    attributes:
      label: How can we reproduce it?
    validations:
      required: true

  - type: input
    attributes:
      label: Library version
      placeholder: "e.g. 1.0.1"
    validations:
      required: true

  - type: input
    attributes:
      label: OS
      placeholder: "e.g. Android 15 (API 35)"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Logs and errors
      render: text
    validations:
      required: false

  - type: textarea
    attributes:
      label: Anything else we need to know
    validations:
      required: false
